---
- hosts: all
  become: yes
  vars:
    - packages:
      - openscap-scanner
      - vim
      - scap-security-guide
      - git

    - repos:
      - 

  tasks:
    - include_vars: rhel_vault.yaml
      no_log: true

    - name: Subscription Manager subscribe
      redhat_subscription:
        state: present
        username: "{{sm_username}}"
        password: "{{sm_password}}"
        auto_attach: true

    - name: upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Install Workstation
      yum:
        name: "{{packages}}"
        state: latest

    - name: Add vagrant to wheel group
      command: "sudo usermod -aG wheel vagrant"

    - name: set timezone to New york
      timezone:
        name: America/New_York

    - name: Copy sweet vim config
      copy:
        src: vim_config/vimrc
        dest: /etc/vimrc

    - name: Set some kernel parameters
      lineinfile:
        dest: "~/.bash_profile"
        insertafter: EOF
        line: " export {{item}}"
      no_log: true
      become_user: vagrant
      with_items:
        - "AWS_ACCESS_KEY_ID={{AWS_ACCESS_KEY_ID}}"
        - "AWS_SECRET_ACCESS_KEY={{AWS_SECRET_ACCESS_KEY}}"
        - "AWS_DEFAULT_REGION={{AWS_DEFAULT_REGION}}"

    - name: Get updated files from git repository
      git:
        repo: https://{{ git_username | urlencode }}:{{ git_password | urlencode }}@{{item}}
        dest: /home/vagrant/share
      with_items: "{{repos}}"


    # - name: Make Sig dir
    #   file: path=/stigs state=directory
    #
    # - name: Initial OpenScap Scan (USGCB/STIG)
    #   command: "sudo oscap xccdf eval --profile ospp-rhel7 --stig-viewer /stigs/initial_stig_results.xml --report /stigs/initial_stig_results.html /usr/share/xml/scap/ssg/content/ssg-rhel7-xccdf.xml"
    #   ignore_errors: yes
    #
    # - name: Remediate OpenScap Scan (USGCB/STIG)
    #   command: "sudo oscap xccdf eval --remediate --profile ospp-rhel7 --stig-viewer /stigs/remediate_stig_results.xml --report /stigs/remediate_stig_results.html /usr/share/xml/scap/ssg/content/ssg-rhel7-xccdf.xml"
    #   ignore_errors: yes
    #
    # - name: Compress directory /path/to/foo/ into /path/to/foo.tgz
    #   archive:
    #     path: /stigs
    #     dest: /stigs/stigs.tgz
    #
    # - name: Copy stig reports
    #   fetch:
    #     src: /stigs/stigs.tgz
    #     dest: /tmp/stigs.tgz
