---
- hosts: all
  become: yes
  vars:

    - rhel_repos:
      - "rhel-7-server-ose-3.9-rpms"
      - "rhel-7-server-ansible-2.6-rpms"

    - openshift_packages:
      - openshift-ansible

    - packages:
      - openscap-scanner
      - vim
      - scap-security-guide
      - git
      - python2-boto3
      - ansible

    - git_host: "bitbucket.di2e.net/scm/ad722et/"

    - git_repos:
      - openshift-ansible-playbooks
      - common-ansible-playbooks
      - atlassian-ansible-playbooks
      - nexus-ansible-playbooks

  tasks:
    - include_vars: rhel_vault.yaml
      no_log: true


    - name: Subscription Manager subscribe
      redhat_subscription:
        state: present
        username: "{{sm_username}}"
        password: "{{sm_password}}"

        auto_attach: true

    - name: Attempt to install RHEL7 Server and Openshift Packages
      block:
        - name: Enable a RHSM repositories
          rhsm_repository:
            name: "{{item}}"
          with_items: "{{rhel_repos}}"
        - name: Install Openshift Workstation
          yum:
            name: "{{openshift_packages}}"
            state: latest
      rescue:
        - debug:
            msg: "Looks like you didnt have a RHEL openshift/server subscription"

    - name: upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Install Workstation
      yum:
        name: "{{packages}}"
        state: latest


    - name: Add vagrant to wheel group
      command: "usermod -aG wheel vagrant"

    - name: set timezone to New york
      timezone:
        name: America/New_York

    - name: Copy sweet vim config
      copy:
        src: vim_config/vimrc
        dest: /etc/vimrc

    - name: Set some kernel parameters
      lineinfile:
        dest: "~/.bash_profile"
        insertafter: EOF
        line: " export {{item}}"
      no_log: true
      become_user: vagrant
      with_items:
        - "AWS_ACCESS_KEY_ID={{AWS_ACCESS_KEY_ID}}"
        - "AWS_SECRET_ACCESS_KEY={{AWS_SECRET_ACCESS_KEY}}"
        - "AWS_DEFAULT_REGION={{AWS_DEFAULT_REGION}}"

    - name: Set git config email
      command:   'git config --global user.email "{{git_email}}"'
      become_user: vagrant

    - name: Set git config email
      command:   'git config --global user.name "{{git_username}}"'
      become_user: vagrant


    - name: Get updated files from git repository
      git:
        repo: https://{{ git_username | urlencode }}:{{ git_password | urlencode }}@{{git_host}}{{item}}.git
        dest: /home/vagrant/share/{{item}}
      with_items: "{{git_repos}}"




    # - name: Make Sig dir
    #   file: path=/stigs state=directory
    #
    # - name: Initial OpenScap Scan (USGCB/STIG)
    #   command: "sudo oscap xccdf eval --profile ospp-rhel7 --stig-viewer /stigs/initial_stig_results.xml --report /stigs/initial_stig_results.html /usr/share/xml/scap/ssg/content/ssg-rhel7-xccdf.xml"
    #   ignore_errors: yes
    #
    # - name: Remediate OpenScap Scan (USGCB/STIG)
    #   command: "sudo oscap xccdf eval --remediate --profile ospp-rhel7 --stig-viewer /stigs/remediate_stig_results.xml --report /stigs/remediate_stig_results.html /usr/share/xml/scap/ssg/content/ssg-rhel7-xccdf.xml"
    #   ignore_errors: yes
    #
    # - name: Compress directory /path/to/foo/ into /path/to/foo.tgz
    #   archive:
    #     path: /stigs
    #     dest: /stigs/stigs.tgz
    #
    # - name: Copy stig reports
    #   fetch:
    #     src: /stigs/stigs.tgz
    #     dest: /tmp/stigs.tgz
