---
- hosts: all
  become: yes
  vars:

    - rhel_repos:
      - "rhel-7-server-ose-3.9-rpms"
      - "rhel-7-server-ansible-2.6-rpms"

    - openshift_packages:
      - openshift-ansible

    - packages:
      - openscap-scanner
      - vim
      - scap-security-guide
      - git
      - python2-boto3
      - python2-boto
      - python2-pip
      - ansible

    - pip_user:
      - awscli

  tasks:
    - include_vars: rhel_vault.yaml
      no_log: true

    - include_vars: repo_vars.yaml


    - name: Subscription Manager subscribe
      redhat_subscription:
        state: present
        username: "{{sm_username}}"
        password: "{{sm_password}}"

        auto_attach: true

    - name: Attempt to install RHEL7 Server and Openshift Packages
      block:
        - name: Enable openshift RHSM repositories
          rhsm_repository:
            name: "{{item}}"
          with_items: "{{rhel_repos}}"
        - name: Install Openshift Workstation
          yum:
            name: "{{openshift_packages}}"
            state: latest
      rescue:
        - debug:
            msg: "Looks like you didnt have a RHEL openshift/server subscription"

    - name: upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Install Workstation
      yum:
        name: "{{packages}}"
        state: latest

    - name: Add vagrant to wheel group
      command: "usermod -aG wheel vagrant"

    - name: set timezone to New york
      timezone:
        name: America/New_York

    - name: Restart crond
      service:
        name: crond
        state: reloaded

    - name: Copy sweet vim config
      copy:
        src: vim_config/vimrc
        dest: /etc/vimrc

    - name: Env parameters
      lineinfile:
        dest: "~/.bash_profile"
        insertafter: EOF
        line: " export {{item}}"
      no_log: true
      become_user: vagrant
      with_items:
        - "AWS_ACCESS_KEY_ID={{AWS_ACCESS_KEY_ID}}"
        - "AWS_SECRET_ACCESS_KEY={{AWS_SECRET_ACCESS_KEY}}"
        - "AWS_DEFAULT_REGION={{AWS_DEFAULT_REGION}}"

    - name: upgrade pip
      shell: "pip install --upgrade pip"

    - name: Install aws tools
      pip:
        name: "{{item}}"
        extra_args: --user
      with_items: "{{pip_user}}"

    - name: Set git config email
      command:   'git config --global user.email "{{git_email}}"'
      become_user: vagrant

    - name: Set git config email
      command:   'git config --global user.name "{{git_username}}"'
      become_user: vagrant

    - name: Get updated files from git repository
      git:
        repo: https://{{ git_username | urlencode }}:{{ git_password | urlencode }}@{{git_host}}{{item}}.git
        dest: /home/vagrant/share/{{item}}
      with_items: "{{git_repos}}"
      when: git_repos is defined and git_host is defined and git_password is defined and git_username is defined
