---
- hosts: all
  become: yes

  vars:
    - packages:
      - "rkt"

  tasks:

    - name: Upgrade system
      pacman:
        update_cache: yes
        upgrade: yes
    - name: install rkt
      pacman:
        name: "{{item}}"
        state: present
      with_items: "{{packages}}"


