---
- hosts: all
  become: yes

  vars:
    - packages:
       - "gvim"
       - "tilix"
       - "atom"

  tasks:

    - name: upgrade all packages
      pacman:
        upgrade: yes
        update_cache: yes

    - name: Install Workstation
      pacman:
        name: "{{packages}}"
        state: latest

    - name: Create share folder
      file:
        path: "/home/vagrant/share"
        owner: vagrant
        group: vagrant
        state: directory

    - name: Copy sweet vim config
      copy:
        src: vim_config/vimrc
        dest: /etc/vimrc


    - name: Get user id
      command: "id -u vagrant"
      register: vagrant_user_id

    - name: "Userid issue"
      debug:
        msg: "User id is: {{vagrant_user_id.stdout}}"


          #     #WARNING this command is not idempotent
          # I am getting extra entries in /etc/fstab
    - name: Mount vboxsf folder
      mount:
        path: /home/vagrant/share
        src: manjaro_share
        fstype: vboxsf
        opts: "uid={{vagrant_user_id.stdout}},gid={{vagrant_user_id.stdout}},rw,dmode=700,fmode=600,noauto,x-systemd.automount"
        state: mounted

    - name: Enable and start vbox services
      systemd:
        name: vboxservice
        state: started
        enabled: True
