---
- hosts: all
  become: yes

  vars:
    - packages:
      - virtualbox-guest-dkms
      - virtualbox-guest-utils

  tasks:
    - include_vars: ubuntu_vault.yaml
      no_log: true

    - name: Install aptitude for ansible apt module
      command: "apt-get -y install aptitude"

    - name: upgrade all packages
      apt:
        name: '*'
        state: latest

    - name: Install Packages
      apt:
        name: "{{packages}}"
        state: latest
